source 'https://github.com/CocoaPods/Specs.git'

target 'ETSegmentedView', :exclusive => true do
  pod "ETSegmentedView", :path => "../"
  
  pod 'pop', '~> 1.0.7'
end

target 'Tests', :exclusive => true do
  pod "ETSegmentedView", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
